=head1 NAME

Net::Statsd::Server::Changes - Change history for Net::Statsd::Server

=head2 Changes in Net::Statsd::Server 0.07   23rd January 2013

  Started converting the nodejs statsd test suite to TAP
    test cases. Completed the conversion of the metrics processing
    test cases. This uncovered two subtle bugs in the metrics class.

  Fixed bug in calculation of percentile values threshold, due
    to a difference in how Javascript's Math.round() and
    Perl's int() work.

  Fixed undefined value warning in the metrics processing during
    the calculation of cumulative values for timers, due to
    an off-by-one error.

=head2 Changes in Net::Statsd::Server 0.06   17th January 2013

  Added new File backend.
    It allows to flush all aggregated stats to a given log file.

  Added keyFlush implementation.
    Allows to have the top n% (keyFlush.percent) dumped to a
    log file (keyFlush.log) or stdout every y seconds
    (keyFlush.interval).

=head2 Changes in Net::Statsd::Server 0.05   16th January 2013

  Improved UDP socket default settings to perform better.
    In my tests, Net::Statsd::Server manages to successfully capture
    almost twice the amount of UDP traffic (otherwise lost) than
    the original node.js based statsd, with SO_RCVBUF = 8Mb.
    I still have to experiment a bit more with this setting though.

=head2 Changes in Net::Statsd::Server 0.04   15th January 2013

  Fixed statistics flush. When a flush is triggered, stats have
    to be cleared. The flush code wasn't doing this previously.

  Fixed management commands (:8126) to output correct JSON data
    structures.

  This is the first fully functional statsd server release.

=head2 Net::Statsd::Server 0.01 - 0.03            January 2013

  First release on an unsuspecting world.

=cut
